"""Cut redteam.yaml (381 generated attacks) down to the evaluated suite:
every plugin attack as written, plus its base64 and jailbreak-templates variants,
plus ONE jailbreak:composite variant per attack. jailbreak:meta is dropped (hosted,
iterative, and most of the cost). The composite pick rotates through each attack's
variants by position, so the choice is deterministic and every variant slot is used.

Run from the repo root:
    .venv/bin/python redteam/subset.py
"""

from __future__ import annotations

import base64
import re
from collections import Counter
from pathlib import Path

import yaml

HERE = Path(__file__).resolve().parent
SRC = HERE / "redteam.yaml"
OUT = HERE / "redteam-subset.yaml"

KEEP = {None, "base64", "jailbreak-templates"}
DROP = {"jailbreak:meta"}


def _repair_injection_query(t: dict) -> None:
    """indirect-prompt-injection tests come back with vars.query undefined: basic sends an
    empty string (Voyage rejects it), base64 sends base64("undefined"), and the templates end
    in the literal word "undefined". The attacker's intended question is in the poisoned
    chunk after "Prompt:"; restore it, transformed the way the test's strategy would have."""
    m = re.match(r"Prompt:\s*(.+?)\s*\[", t["vars"]["context"], re.S)
    if not m:
        raise SystemExit(f"no 'Prompt:' question in injection context: {t['vars']['context'][:80]!r}")
    question = m.group(1)
    strategy = t["metadata"].get("strategyId")
    if strategy is None:
        t["vars"]["query"] = question
    elif strategy == "base64":
        t["vars"]["query"] = base64.b64encode(question.encode()).decode()
    elif strategy == "jailbreak-templates" and t["vars"]["query"].count("undefined") == 1:
        t["vars"]["query"] = t["vars"]["query"].replace("undefined", question)
    else:
        raise SystemExit(f"cannot repair injection query for strategy {strategy}")


class _NoAliases(yaml.SafeDumper):
    def ignore_aliases(self, data):
        return True


def main() -> None:
    cfg = yaml.safe_load(SRC.read_text(encoding="utf-8"))
    kept, composite = [], {}
    for t in cfg["tests"]:
        strategy = t.get("metadata", {}).get("strategyId")
        if t["metadata"]["pluginId"] == "indirect-prompt-injection" and strategy in KEEP:
            _repair_injection_query(t)
        if strategy in KEEP:
            kept.append(t)
        elif strategy == "jailbreak:composite":
            composite.setdefault(t["metadata"]["originalText"], []).append(t)
        elif strategy not in DROP:
            raise SystemExit(f"unexpected strategy: {strategy}")

    for i, variants in enumerate(composite.values()):
        kept.append(variants[i % len(variants)])

    cfg["tests"] = kept
    OUT.write_text(
        "# Generated by redteam/subset.py from redteam.yaml. Do not edit by hand.\n"
        + yaml.dump(cfg, Dumper=_NoAliases, sort_keys=False, allow_unicode=True, width=100),
        encoding="utf-8",
    )

    by = Counter((t["metadata"].get("strategyId") or "basic") for t in kept)
    print(f"{len(kept)} tests -> {OUT.relative_to(HERE.parent)}")
    for k, v in sorted(by.items()):
        print(f"  {k:<22} {v}")
    print(Counter(t["metadata"]["pluginId"] for t in kept))


if __name__ == "__main__":
    main()
